//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Video_Copy6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myVideoEntities : DbContext
    {
        public myVideoEntities()
            : base("name=myVideoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_CONFIG> T_CONFIG { get; set; }
        public virtual DbSet<T_COPYACTION> T_COPYACTION { get; set; }
        public virtual DbSet<T_COPYACTION_SUB> T_COPYACTION_SUB { get; set; }
        public virtual DbSet<T_DISK_INFO> T_DISK_INFO { get; set; }
        public virtual DbSet<T_Logs> T_Logs { get; set; }
        public virtual DbSet<T_Tages> T_Tages { get; set; }
        public virtual DbSet<T_Video> T_Video { get; set; }
        public virtual DbSet<T_Video_Tags> T_Video_Tags { get; set; }
        public virtual DbSet<T_WORKS> T_WORKS { get; set; }
        public virtual DbSet<T_WORKS_SUB> T_WORKS_SUB { get; set; }
    }
}
