//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Video_Copy6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DISK_INFO
    {
        public long ID { get; set; }
        public string PHYSICAL_NAME { get; set; }
        public Nullable<double> PHYSCIAL_TOTALSIZE { get; set; }
        public string LOGICAL_NAME { get; set; }
        public Nullable<double> LOGICAL_TOTALSIZE { get; set; }
        public Nullable<double> LOGICAL_USESPACE { get; set; }
        public Nullable<double> LOGICAL_FREESPACE { get; set; }
        public Nullable<double> LOGICAL_PERCENT { get; set; }
        public bool IS_ONLINE { get; set; }
        public string FIELD1 { get; set; }
        public string FIELD2 { get; set; }
        public string FIELD3 { get; set; }
        public string FIELD4 { get; set; }
    }
}
