//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Video_Copy6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Video
    {
        public long ID { get; set; }
        public string FILE_INDEX { get; set; }
        public string FILE_NAME { get; set; }
        public string Device_UID { get; set; }
        public string FILE_ROOT { get; set; }
        public string FILE_DIR { get; set; }
        public string FILE_FULLPATH { get; set; }
        public string FILE_EXTENSION { get; set; }
        public Nullable<double> FILESIZE { get; set; }
        public Nullable<System.DateTime> FILE_CREATE_TIME { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string FIELD1 { get; set; }
        public string FIELD2 { get; set; }
        public string FIELD3 { get; set; }
        public string FIELD4 { get; set; }
    }
}
