//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Video_Copy6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WORKS_SUB
    {
        public long ID { get; set; }
        public long PID { get; set; }
        public Nullable<long> ID_VIDEO { get; set; }
    }
}
