//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Video_Copy6
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WORKS
    {
        public long ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string TARGET_LOCATION { get; set; }
        public Nullable<long> VIDEO_COUNT { get; set; }
        public Nullable<double> TARGET_HD_SIZE { get; set; }
        public string MEMO { get; set; }
        public Nullable<double> SOURCE_SIZE { get; set; }
        public Nullable<long> COPY_COUNT { get; set; }
        public Nullable<double> TARGET_FREE_SIZE { get; set; }
    }
}
